---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: default
spec:
  provider: lastpass
  parameters:
    # share is the LastPass shared folder name. If set, it must have prefix "Shared-"
    # group is the LastPass folder name (can be within or outside a shared folder)
    # name is the LastPass item / account / password name
    items: |
      - share: ""
        group: ""
        name: "netflix"

  # Everything below here is OPTIONAL.
  #
  # If you not only want your LastPass item defined above be mounted to the Pod,
  # but additionally create a K8s Secret object containing the LastPass item,
  # define the desired state of the synced K8s secret object here:
  secretObjects:
  - data:
      # Choose some arbitrary key.
    - key: mykey
      # Name of the mounted content to sync.
      # In our example the secret will be mounted to /mnt/secrets-store/netflix
      # (Note: If your item above defines group 'my-group', the secret will be mounted into
      # /mnt/secrets-store/my-group/netflix and you will therefore need to set the
      # objectName to 'my-group/netflix'.)
      objectName: netflix
    # Choose some arbitrary name of the K8s Secret object
    # that will be created by Secrets Store CSI Driver.
    secretName: mysecret
    type: Opaque
