---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: default
spec:
  provider: lastpass
  parameters:
    # share is the LastPass shared folder name. If set, it must have prefix "Shared-"
    # group is the LastPass folder name (can be within or outside a shared folder)
    # name is the LastPass item / account / password name
    items: |
      - share: ""
        group: ""
        name: "name1"
      # - share: ""
        # group: "group1"
        # name: "name2"
      # - share: "Shared-team1"
        # group: ""
        # name: "name3"
