---
apiVersion: v1
kind: Secret
metadata:
  name: lastpass-credentials
  namespace: default
  labels:
    # "This label needs to be set for all nodePublishSecretRef."
    # https://secrets-store-csi-driver.sigs.k8s.io/load-tests.html#understanding-secrets-store-csi-driver-memory-consumption
    secrets-store.csi.k8s.io/used: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ((lastpass-username))
  password: ((lastpass-masterpassword))
